### PR TITLE
[WIP] Fix null check issue

### PR DESCRIPTION
**Pull request by sagikazarmark**
@joelwurtz this should solve #20, but I have no idea how to test it.

### CODE REVIEW

**Comment by sagikazarmark** [comment]
Forget it, this solution sucks. But I would still need one @joelwurtz :wink:

**Comment by sagikazarmark** [comment]
Finally I was able to wrap this up, although it needs to be checked if it is a valid approach. Also, no tests are added.

What's happening:

- In denormalization `property_exists` is used instead of isset. Is this correct at all?
- In normalization if the property is a single null value, then it is always set to null. If it has multiple types with null one of them, setting null is added to the else clause.

**Comment by joelwurtz** [comment]
Working on a fix right now,

In fact i add a nullable field when guessing the property, then on the generation i just gave to check this nullable field.

**Comment by joelwurtz** [comment]
Will also add a better test workflow after this

**Comment by sagikazarmark** [comment]
Sounds good. :+1:

**Comment by joelwurtz** [comment]
Closed in favor of #23

**Pull request closed without merging**
